### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [sevenineone/cmdRleCoding#1]
1. https://github.com/sevenineone/cmdRleCoding/blob/fe3a2ba1f500a4977980e6cd14ec2f312a492d33/src/main/java/rle/Rle.java#L24 Это лишняя строчка. Если предыдущее условие выполняется, то присваивать незачем, а если не выполняется, то Вы выйдете из цикла и до этой строчки не дойдёте.
1. https://github.com/sevenineone/cmdRleCoding/blob/fe3a2ba1f500a4977980e6cd14ec2f312a492d33/src/main/java/rle/Rle.java#L16 Вместо `String` следует использовать `StringBuilder`. А ещё лучше объявить эту переменную внутри `if`, в котором она используется.
1. https://github.com/sevenineone/cmdRleCoding/blob/fe3a2ba1f500a4977980e6cd14ec2f312a492d33/src/main/java/rle/Rle.java#L38-L39 Лучше `-num` в строку перевести.
1. Используйте вместо 48 символ 0.
1. https://github.com/sevenineone/cmdRleCoding/blob/fe3a2ba1f500a4977980e6cd14ec2f312a492d33/src/main/java/rle/Rle.java#L79-L82 Не нужно разбивать открытие файла на два `try`, можно оставить по одному на входной и выходной файл.
1. Не используйте абсолютные пути в тестах, иначе их сможете запустить только Вы.
1. Зачем Вы закоммитили выходные файлы и не используете их? Либо не коммитьте их совсем, либо положите куда-то в другое место и используйте как эталонные.

**Comment by sevenineone** [comment]
Так, вроде все поправил, все по красоте)

**Comment by maximpetrov** [comment]
1. Вы как-то очень "топорно" заменили `String` на `StringBuilder`. Во-первых, у `StringBuilder` есть перегруженная версия `append` для добавления `char`, не нужно его предварительно в строку переводить. Во-вторых, `substring` у `StringBuilder` тоже есть, `toString()` перед этим делать тоже лишнее.
1. В 5 пункте я имел в виду, что стоит вообще избавиться от лишней промежуточной переменной: `try (InputStreamReader reader = new InputStreamReader(new FileInputStream(inputName)))`
1. Решение с вычислением `path` в тестах, конечно, тоже работает, но проще было бы использовать относительные пути, то есть путь относительно текущего каталога (как у Вас сейчас, но без `path` и начальных слешей.

**Comment by sevenineone** [comment]
Я поправил, но если я не перевожу в строку при использовании`append`, то он их выводит как ascii code.

**Comment by maximpetrov** [comment]
Да, действительно, это происходит потому, что у Вас переменная `int`, а не `char`. Тогда приведите её к `char` при добавлении, это лучше, чем переводить в строку. (`(char)sym`)

**Comment by maximpetrov** [comment]
https://github.com/sevenineone/cmdRleCoding/blob/c96ff8e59340d4be5da26d25a216a4e694f7800f/src/main/java/rle/Rle.java#L36 Тут `toString()` так и не убрали.
